name: Merge main changes into develop
run-name: Merging main changes into develop

on: workflow_dispatch

jobs:
  Sync-Upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Add upstream remote
        run: git remote add upstream https://github.com/splitti/MuPiBox.git

      - name: Set user name
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: Merge new tags into develop one by one
        run: |
          NEWTAGS=$(git fetch --tags --force upstream 2>&1 | awk '/\[new tag\]/ {print $4}')
          git fetch --tags --force
          for tag in ${NEWTAGS[@]}
          do
            git merge --no-edit ${tag}

            # modify version.json splitti -> friebi
            sed --in-place s/splitti/friebi/g version.json

            # commit it
            git add version.json
            git commit --message="v${tag}"
            git tag --force ${tag}
          done

      - name: Merge remaining changes from main
        run: git merge --no-edit origin/main

      - name: Push everything
        run: |
          git push
          git push --tags
